#!/bin/sh -l 
# FILENAME:  phosim_runlong4.sub 
cd /home/dutta26/Downloads/phosim_core/ 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10015/  
./phosim examples/odi_catalog/15_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10015/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10016/  
./phosim examples/odi_catalog/16_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10016/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10017/  
./phosim examples/odi_catalog/17_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10017/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10018/  
./phosim examples/odi_catalog/18_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10018/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10019/  
./phosim examples/odi_catalog/19_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10019/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
