#!/bin/sh -l 
# FILENAME:  phosim_runlong2.sub 
cd /home/dutta26/Downloads/phosim_core/ 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1005/  
./phosim examples/odi_catalog/5_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1005/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1006/  
./phosim examples/odi_catalog/6_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1006/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1007/  
./phosim examples/odi_catalog/7_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1007/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1008/  
./phosim examples/odi_catalog/8_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1008/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1009/  
./phosim examples/odi_catalog/9_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1009/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
