#!/bin/sh -l 
# FILENAME:  phosim_runlong5.sub 
cd /home/dutta26/Downloads/phosim_core/ 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10019/  
./phosim examples/odi_catalog/19_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10019/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10014/  
./phosim examples/odi_catalog/14_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/10014/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1009/  
./phosim examples/odi_catalog/9_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1009/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1004/  
./phosim examples/odi_catalog/4_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1004/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
