#!/bin/sh -l 
# FILENAME:  phosim_runlong1.sub 
cd /home/dutta26/Downloads/phosim_core/ 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1001/  
./phosim examples/odi_catalog/1_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1001/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1002/  
./phosim examples/odi_catalog/2_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1002/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1003/  
./phosim examples/odi_catalog/3_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1003/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1004/  
./phosim examples/odi_catalog/4_long.txt -i wiyn_odi -c examples/nobackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_long/1004/ -w /scratch/halstead/d/dutta26/abell_2390/work_long  
