#!/bin/sh -l 
# FILENAME:  phosim_run_star4.sub 
cd /home/dutta26/apps/phosim-phosim_release-2479c7396c0c/  
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10040/  
./phosim examples/odi_catalog/40_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10040/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10041/  
./phosim examples/odi_catalog/41_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10041/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10042/  
./phosim examples/odi_catalog/42_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10042/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10043/  
./phosim examples/odi_catalog/43_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10043/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10044/  
./phosim examples/odi_catalog/44_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10044/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10045/  
./phosim examples/odi_catalog/45_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10045/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10046/  
./phosim examples/odi_catalog/46_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10046/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10047/  
./phosim examples/odi_catalog/47_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10047/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10048/  
./phosim examples/odi_catalog/48_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10048/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
mkdir /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10049/  
./phosim examples/odi_catalog/49_star.txt -i wiyn_odi -c examples/quickbackground -o /scratch/halstead/d/dutta26/abell_2390/odi_img_star/10049/ -w /scratch/halstead/d/dutta26/abell_2390/work_star -t 4 
