#!/bin/sh -l
# FILENAME:  g_coadd.sub

module load anaconda/2020.11-py38
source activate /home/dutta26/.conda/envs/cent7/2020.11-py38/test

cd /home/dutta26/codes/makeWeights/
#python makeWeights.py /scratch/bell/dutta26/abell_2390/g/
python makeFileList.py /scratch/bell/dutta26/abell_2390/g/ /home/dutta26/codes/makeWeights/fileList_swarp_g.ascii



swarp @/home/dutta26/codes/makeWeights/fileList_swarp_g.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/bell/dutta26/abell_2390/abell_g_coadd.fits -WEIGHTOUT_NAME /scratch/bell/dutta26/abell_2390/abell_g_coadd.weight.fits -RESAMPLE_DIR /scratch/bell/dutta26/abell_2390/ -RESCALE_WEIGHTS N

#swarp @/home/dutta26/codes/makeWeights/fileList_swarp_g.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/bell/dutta26/abell_2390/abell_g_coadd_withBkg.fits -WEIGHTOUT_NAME /scratch/bell/dutta26/#abell_2390/abell_g_coadd_withBkg.weight.fits -RESAMPLE_DIR /scratch/bell/dutta26/abell_2390/ -RESCALE_WEIGHTS N
