#!/bin/sh -l
# FILENAME:  ir_coadd.sub

module load anaconda/2020.11-py38
source activate /home/dutta26/.conda/envs/cent7/2020.11-py38/test


#swarp @/home/dutta26/codes/makeWeights/fileList_swarp_ir.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/bell/dutta26/abell_2390/abell_ir_coadd.fits -WEIGHTOUT_NAME /scratch/bell/dutta26/abell_2390/#abell_ir_coadd.weight.fits -RESAMPLE_DIR /scratch/bell/dutta26/abell_2390/ -RESCALE_WEIGHTS N



swarp @/home/dutta26/codes/makeWeights/fileList_swarp_ir_med.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/bell/dutta26/abell_2390/abell_ir_coadd_med.fits -WEIGHTOUT_NAME /scratch/bell/dutta26/abell_2390/abell_ir_coadd_med.weight.fits -RESAMPLE_DIR /scratch/bell/dutta26/abell_2390/ -RESCALE_WEIGHTS N
