#!/bin/sh -l
# FILENAME:  myjob_swarp_g.sub

module load anaconda/2020.11-py38
source activate /home/dutta26/.conda/envs/cent7/5.1.0-py27/test
cd /home/dutta26/codes/makeWeights/
#python makeWeights.py /scratch/halstead/d/dutta26/abell_2390/z/
python makeFileList.py /scratch/halstead/d/dutta26/abell_2390/z/ /home/dutta26/codes/makeWeights/fileList_swarp_z.ascii

cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/codes/makeWeights/fileList_swarp_z.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_z_coadd_wted.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_z_coadd_wted.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/

#################################################################################

module load anaconda
source activate test
cd /home/dutta26/codes/makeWeights/
#python makeWeights.py /scratch/halstead/d/dutta26/abell_2390/g/
python makeFileList.py /scratch/halstead/d/dutta26/abell_2390/g/ /home/dutta26/codes/makeWeights/fileList_swarp_g.ascii


cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/codes/makeWeights/fileList_swarp_g.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_g_coadd_wted.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_g_coadd_wted.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/

###########################################################################################

module load anaconda
source activate test
cd /home/dutta26/codes/makeWeights/
#python makeWeights.py /scratch/halstead/d/dutta26/abell_2390/r/
python makeFileList.py /scratch/halstead/d/dutta26/abell_2390/r/ /home/dutta26/codes/makeWeights/fileList_swarp_r.ascii


cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/codes/makeWeights/fileList_swarp_r.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_r_coadd_wted.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_r_coadd_wted.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/

###########################################################################################

module load anaconda
source activate test
cd /home/dutta26/codes/makeWeights/
#python makeWeights.py /scratch/halstead/d/dutta26/abell_2390/i/
python makeFileList.py /scratch/halstead/d/dutta26/abell_2390/i/ /home/dutta26/codes/makeWeights/fileList_swarp_i.ascii


cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/codes/makeWeights/fileList_swarp_i.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_i_coadd_wted.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_i_coadd_wted.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/

#######################################################################

module load anaconda
source activate test
cd /home/dutta26/codes/makeWeights/
#python makeWeights.py /scratch/halstead/d/dutta26/abell_2390/u/
python makeFileList.py /scratch/halstead/d/dutta26/abell_2390/u/ /home/dutta26/codes/makeWeights/fileList_swarp_u.ascii


cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/codes/makeWeights/fileList_swarp_u.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_u_coadd_wted.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_u_coadd_wted.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/
###############################################################################################
#Now coadd IR 
#Make file list 

cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/file_list.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_wted1.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_wted1.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/

#Crop the coadded file 
cd /home/dutta26/codes/makeWeights/
python makeFinalCuts.py /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_wted1.fits /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_wted.fits 
python makeFinalCuts.py /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_wted1.weight.fits /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_wted.weight.fits

#Sextract the images 
cd /home/dutta26/Downloads/sextractor-2.19.5/share/sextractor/
./sex /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_crop.fits 

#Create starlist for GAIA EDR 3 
cd /home/dutta26/codes/makeCuts/
python seperate_star_gal.py /home/dutta26/Downloads/sextractor-2.19.5/share/sextractor/test.cat /home/dutta26/codes/source_list.pk1 /scratch/halstead/d/dutta26/abell_2390/abell_ir_coadd_crop.fits

python coadd_detect.py ir /home/dutta26/codes/source_list.pk1
python coadd_detect.py u /home/dutta26/codes/source_list.pk1
python coadd_detect.py g /home/dutta26/codes/source_list.pk1
python coadd_detect.py r /home/dutta26/codes/source_list.pk1
python coadd_detect.py i /home/dutta26/codes/source_list.pk1
python coadd_detect.py z /home/dutta26/codes/source_list.pk1


python single_frame_detect.py u /home/dutta26/codes/source_list.pk1
python single_frame_detect.py g /home/dutta26/codes/source_list.pk1
python single_frame_detect.py r /home/dutta26/codes/source_list.pk1
python single_frame_detect.py i /home/dutta26/codes/source_list.pk1
python single_frame_detect.py z /home/dutta26/codes/source_list.pk1








