#!/bin/sh -l
# FILENAME:  r_coadd.sub

module load anaconda/2020.11-py38
source activate /home/dutta26/.conda/envs/cent7/2020.11-py38/test

cd /home/dutta26/codes/makeWeights/
#python makeWeights.py /scratch/bell/dutta26/abell_2390/r/
#python makeFileList.py /scratch/bell/dutta26/abell_2390/r/ /home/dutta26/codes/makeWeights/fileList_swarp_r.ascii



#swarp @/home/dutta26/codes/makeWeights/fileList_swarp_r.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/bell/dutta26/abell_2390/abell_r_coadd.fits -WEIGHTOUT_NAME /scratch/bell/dutta26/abell_2390/#abell_r_coadd.weight.fits -RESAMPLE_DIR /scratch/bell/dutta26/abell_2390/ -RESCALE_WEIGHTS N







swarp @/home/dutta26/codes/makeWeights/fileList_swarp_r.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/bell/dutta26/abell_2390/abell_r_coadd_med.fits -WEIGHTOUT_NAME /scratch/bell/dutta26/abell_2390/abell_r_coadd_med.weight.fits -RESAMPLE_DIR /scratch/bell/dutta26/abell_2390/ -COMBINE_TYPE MEDIAN
