#!/bin/sh -l
# FILENAME:  myjob_swarp_g.sub

module load anaconda
source activate /home/dutta26/.conda/envs/cent7/5.1.0-py27/test



cd /home/dutta26/codes/makeWeights/
python makeFileList.py /scratch/halstead/d/dutta26/abell_2390/u/ /home/dutta26/codes/makeWeights/fileList_swarp_u.ascii


cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/codes/makeWeights/fileList_swarp_u.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_u_coadd_wted.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_u_coadd_wted.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/



cd /home/dutta26/codes/makeWeights/
python makeFileList.py /scratch/halstead/d/dutta26/abell_2390/z/ /home/dutta26/codes/makeWeights/fileList_swarp_z.ascii


cd /home/dutta26/apps/bin/bin/
./swarp @/home/dutta26/codes/makeWeights/fileList_swarp_z.ascii -c /home/dutta26/default.swarp -IMAGEOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_z_coadd_wted.fits -WEIGHTOUT_NAME /scratch/halstead/d/dutta26/abell_2390/abell_z_coadd_wted.weight.fits -RESAMPLE_DIR /scratch/halstead/d/dutta26/abell_2390/


