#!/bin/sh -l 
# FILENAME:  phosim_lsst1.sub 

cd 


#cd /home/dutta26/apps/phosim-phosim_release-2479c7396c0c/  

#mkdir /scratch/halstead/d/dutta26/lsst/filter0/1008/  
#./phosim /scratch/halstead/d/dutta26/lsst/lsst_catalog1/8.txt_sheared -i lsst -c examples/quickbackground -o /scratch/halstead/d/dutta26/lsst/filter0/1008/ -w /scratch/halstead/d/dutta26/lsst/work1 
#mkdir /scratch/halstead/d/dutta26/lsst/filter0/1008_flat/  
#./phosim /scratch/halstead/d/dutta26/lsst/lsst_catalog1/8.txt_flat -i lsst -c examples/nobackground -o /scratch/halstead/d/dutta26/lsst/filter0/1008_flat/ -w /scratch/halstead/d/dutta26/lsst/work1 


#mkdir /scratch/halstead/d/dutta26/lsst/filter0/10012/  
#./phosim /scratch/halstead/d/dutta26/lsst/lsst_catalog1/12.txt_sheared -i lsst -c examples/quickbackground -o /scratch/halstead/d/dutta26/lsst/filter0/10012/ -w /scratch/halstead/d/dutta26/lsst/work1 
#mkdir /scratch/halstead/d/dutta26/lsst/filter0/10012_flat/  
#./phosim /scratch/halstead/d/dutta26/lsst/lsst_catalog1/12.txt_flat -i lsst -c examples/nobackground -o /scratch/halstead/d/dutta26/lsst/filter0/10012_flat/ -w /scratch/halstead/d/dutta26/lsst/work1 

#module load anaconda/2020.11-py38
#source activate /home/dutta26/.conda/envs/cent7/5.1.0-py27/test
#cd /home/dutta26/codes/lsst_proj/
#python makeCoadd_LSST.py
