#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  4 09:14:42 2022

@author: dutta26
"""

import numpy as np
import pandas as pd
coadd_data_g = pd.read_pickle('/home/dutta26/codes/coaddSc_new_g_.pk1')
coadd_data_g = np.array(coadd_data_g)

coadd_data_r = pd.read_pickle('/home/dutta26/codes/coaddSc_new_r_.pk1')
coadd_data_r = np.array(coadd_data_r)

coadd_data_i = pd.read_pickle('/home/dutta26/codes/coaddSc_new_i_.pk1')
coadd_data_i = np.array(coadd_data_i)

coadd_data_z = pd.read_pickle('/home/dutta26/codes/coaddSc_new_z_.pk1')
coadd_data_z = np.array(coadd_data_z)

coadd_data_u = pd.read_pickle('/home/dutta26/codes/coaddSc_new_u_.pk1')
coadd_data_u = np.array(coadd_data_u)

a,b = np.shape(coadd_data_g)


tempInd = np.where((coadd_data_u[:, 18] == 0) | (coadd_data_u[:, 18] >32 ) | (coadd_data_u[:, 18] <10 ))
mag_u = coadd_data_u[:, 18]
mag_u[tempInd[0]] = -99
err_u = np.sqrt(np.power(10,0.4*(20.554622-coadd_data_u[:, 18])))/(10*np.power(10,0.4*(20.554622-coadd_data_u[:, 18])))
err_u[tempInd[0]] = -99
print (len(tempInd[0]))

tempInd = np.where((coadd_data_g[:, 18] == 0) | (coadd_data_g[:, 18] >32 ) | (coadd_data_g[:, 18] <10 ))
mag_g = coadd_data_g[:, 18]
mag_g[tempInd[0]] = -99
err_g = np.sqrt(np.power(10,0.4*(20.554622-coadd_data_g[:, 18])))/(10*np.power(10,0.4*(20.554622-coadd_data_g[:, 18])))
err_g[tempInd[0]] = -99
print (len(tempInd[0]))

tempInd = np.where((coadd_data_r[:, 18] == 0) | (coadd_data_r[:, 18] >32 ) | (coadd_data_r[:, 18] <10 ))
mag_r = coadd_data_r[:, 18]
mag_r[tempInd[0]] = -99
err_r = np.sqrt(np.power(10,0.4*(20.554622-coadd_data_r[:, 18])))/(10*np.power(10,0.4*(20.554622-coadd_data_r[:, 18])))
err_r[tempInd[0]] = -99
print (len(tempInd[0]))


tempInd = np.where((coadd_data_i[:, 18] == 0) | (coadd_data_i[:, 18] >32 ) | (coadd_data_i[:, 18] <10 ))
mag_i = coadd_data_i[:, 18]
mag_i[tempInd[0]] = -99
err_i = np.sqrt(np.power(10,0.4*(20.554622-coadd_data_i[:, 18])))/(10*np.power(10,0.4*(20.554622-coadd_data_i[:, 18])))
err_i[tempInd[0]] = -99
print (len(tempInd[0]))


tempInd = np.where((coadd_data_z[:, 18] == 0) | (coadd_data_z[:, 18] >32 ) | (coadd_data_z[:, 18] <10 ))
mag_z = coadd_data_z[:, 18]
mag_z[tempInd[0]] = -99
err_z = np.sqrt(np.power(10,0.4*(20.554622-coadd_data_z[:, 18])))/(10*np.power(10,0.4*(20.554622-coadd_data_z[:, 18])))
err_z[tempInd[0]] = -99
print (len(tempInd[0]))


# =============================================================================
# outfile = '/home/dutta26/A2390_mag.in'
# f = open(outfile, mode='w+')
# 
# for j in range(a):
#     f.write(str(j) + ' ' + str(mag_u[j])+ ' '+ str(err_u[j])+ ' '+
#             str(mag_g[j])+ ' '+ str(err_g[j])+ ' ' + 
#             str(mag_r[j])+ ' '+ str(err_r[j])+ ' '+
#             str(mag_i[j])+ ' '+ str(err_i[j])+ ' '+
#             str(mag_z[j])+ ' '+ str(err_z[j])+ ' '+' \n')
#     
# f.close()
# 
# 
# =============================================================================
